=== benjaminramirezg/javaNLParsing/grammars/FSA.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT FSA (states,arcs,tags)>
<!ELEMENT states (state+)>
<!ELEMENT arcs (arc+)>
<!ELEMENT tags (type+)>
<!ELEMENT state EMPTY>
<!ELEMENT arc EMPTY>
<!ELEMENT type (feature+)>
<!ELEMENT feature (value+)>
<!ELEMENT value EMPTY>

<!ATTLIST state id CDATA #REQUIRED>
<!ATTLIST state isFinalState (true|false) #REQUIRED>
<!ATTLIST state isInitialState (true|false) #REQUIRED>
<!ATTLIST state message CDATA #REQUIRED>

<!ATTLIST arc initialState  CDATA #REQUIRED>
<!ATTLIST arc finalState  CDATA #REQUIRED>
<!ATTLIST arc tag CDATA #REQUIRED>

<!ATTLIST type id CDATA #REQUIRED>
<!ATTLIST type name CDATA #REQUIRED>

<!ATTLIST feature name  CDATA #REQUIRED>
<!ATTLIST value value  CDATA #REQUIRED>

=== benjaminramirezg/javaNLParsing/grammars/FSA.xml
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE FSA SYSTEM "./FSA.dtd">

<FSA>
<states>
<state id="1" isFinalState="false" isInitialState="true" message=" "/>
<state id="2" isFinalState="false" isInitialState="false" message="B-NP"/>
<state id="3" isFinalState="true" isInitialState="false" message="I-NP"/>
</states>

<arcs>
<arc initialState="1" finalState="2" tag="1"/>
<arc initialState="2" finalState="3" tag="2"/>
</arcs>

<tags>

<type id="1" name="det">
<feature name="0">
<value value="D"/>
</feature>
<feature name="1"> 
<value value="A"/>
</feature>
</type>

<type id="2" name="noun">
<feature name="0">
<value value="N"/>
</feature>
<feature name="1">
<value value="C"/>
</feature>
</type>

</tags>

</FSA>
